package-lock.json
package.json
pankosmia_metadata.json
src/App.jsx
src/components/DataOut.jsx

Implement Export USFM component, thanks to @eliaspinero !!!!

Export USFM

---

src/App.jsx
src/index.jsx

- Eliminates FAB interference with row action buttons
- Shows the full bottom row of a full page, with the bottom margin also visible.

Full Page+ Height Fixes

---

pankosmia_metadata.json
src/App.jsx
src/components/FabPlusMenu.jsx

Features
- Less quirky table
- Extend FAB, smaller and top-left
~~TODO - fix the offsets and scrolling.~~ **DONE**

Table with borders, FAB icon top left

---

src/App.jsx

This is a fix to the bug that has the scrollbar hidden though still working.  This is one way of bringing the scrollbar back into view.
| Before | After |
| ----- | ---- |
| ![image](https://github.com/user-attachments/assets/52b8068b-79bf-4bee-b695-e862da8e17c4) | ![image](https://github.com/user-attachments/assets/9690bd31-f6e8-46d0-9659-1da82b79cc2e) |

Include scrollbar onscreen

---

src/components/FabPlusMenu.jsx

changement de la couleur du bouton add sur la page content en fonction de couleur du secondary dans le fichier default.json

changement de la couleur du bouton add

---

package-lock.json
package.json
pankosmia_metadata.json
src/App.jsx

Changed the initial values of the columns, the text size, added the i18n for spanish and french and made it scrollable.

Implemented Mark's data grid

---

src/components/NewTextTranslationContent.jsx

résolution du problème de champ caché par le titre dans l'onglet traduction (texte)

probleme de champ caché resolu

---

src/App.jsx
src/components/FabPlusMenu.jsx
src/components/NewBcvContent.jsx
src/components/NewTextTranslationContent.jsx

Ajout sans recharger la page pour voir les contenus qui viennent d'être crées, sur la page content

ajout automatique sur le tableau de content des nouveaux book ou note

---

src/App.jsx

This PR addresses issue #39.
Added alphabetical sorting to the initial state of the Data Grid.

Added default alphabetical sorting to table. #39

---

src/App.jsx

This PR addresses issue #37 .
Added proper padding. Top padding and Left padding.

Added proper padding. #37

---

pankosmia_metadata.json
src/components/FabPlusMenu.jsx

changement des mots pour télécharger du contenu (seulement en anglais) issue #42

changement des noms en anglais pour le telechargement du contenu

---

pankosmia_metadata.json
src/App.jsx
src/components/ArchiveContent.jsx
src/components/ContentRowButtonPlusMenu.jsx
src/components/CopyContent.jsx
src/components/DataGridComponent.jsx
src/components/DeleteContent.jsx
src/components/QuarantineContent.jsx
src/components/RestoreContent.jsx

This PR addresses issue #50 
- Added the CopyContent, ArchiveContent, QuarantineContent and RestoreContent components.
- Refactored the DataGrid to be a component.
- Added i18n for each. (French and Spanish)

Copy, Archive, Quarantine and Restore repo functionalities. #50

---

pankosmia_metadata.json
src/components/AddAndCommit.jsx
src/components/ArchiveContent.jsx
src/components/Commits.jsx
src/components/ContentRowButtonPlusMenu.jsx

This PR addresses the issue #67 
Added the new repo status component:

Repo status component.

---

src/components/RemoteContent.jsx

Replaced the regex with some simple remoteUrl.startsWith("https://")

Small remote url check fix.

---

pankosmia_metadata.json
src/components/RemoteContent.jsx

This PR addresses issue #74 
Added the select branch functionality.

Branch management

---

package-lock.json
pankosmia_metadata.json
src/components/AddAndCommit.jsx
src/components/ArchiveContent.jsx
src/components/Commits.jsx
src/components/ContentRowButtonPlusMenu.jsx
src/components/CopyContent.jsx
src/components/PushToDcs.jsx
src/components/QuarantineContent.jsx
src/components/RestoreContent.jsx

This PR addresses issue #31 
Added the Push to DCS component, fixed some minor styling for other components and made the i18n.

Upload project to Door43 component

---

pankosmia_metadata.json
src/components/ContentRowButtonPlusMenu.jsx
src/components/VersionManager.jsx

This PR addresses issue #81
Added the Drawer component as requested:

Added the VersionManager Drawer component. #81

---

src/App.jsx
src/components/AddAndCommit.jsx
src/components/Commits.jsx
src/components/ContentRowButtonPlusMenu.jsx
src/components/DataGridComponent.jsx
src/components/NewBcvContent.jsx
src/components/NewTextTranslationBook.jsx
src/components/NewTextTranslationContent.jsx
src/components/RemoteContent.jsx

This PR addresses issue #84 
I think I did everything requested, let me know how it looks!

Optimized the content page as requested.

---

pankosmia_metadata.json
src/components/ContentRowButtonPlusMenu.jsx
src/components/SettingsTab.jsx
src/components/VersionManager.jsx

This PR addresses issue #80 
Added all the things requested, and I also added a little Popover TextField for the Add Branch button, since this button is useless if we don't give a name to the branch. So let me know what can I do to make that look better (I just did what came to mind).

Settings tab

---

src/components/ContentRowButtonPlusMenu.jsx

This PR addresses issue #95 
Just removed everything that isn't needed. Including the fetch that stopped being used.

Removed the extra options that are already included in VersionManager

---

src/components/ContentRowButtonPlusMenu.jsx

Re ordered the content options as requested.

Re ordered the content options.
